### PR TITLE
FIx broken int variable type parsing

### PR DESCRIPTION
**Pull request by micimize**

### CODE REVIEW

**Comment by micimize** [comment]
@thosakwe can you comment here when this is released?

**Comment by thosakwe** [comment]
Sorry for the wait: https://pub.dev/packages/graphql_parser/versions/1.1.4

**Comment by micimize** [comment]
@thosakwe you need to publish a new version of `graphql_server`

**Comment by micimize** [comment]
@thosakwe You republished the wrong package, this change was to `graphql_server`

**Comment by thosakwe** [comment]
Ah, I see. My fault! https://pub.dev/packages/graphql_server/versions/1.0.2

**Pull request merged**
